#!/usr/bin/env python3
"""
Prerender the site's explanatory pages as standalone HTML.

WHY
---
17 React routes all serve the same 313-word shell, because content only exists
after JavaScript runs. Google judged the site on that and refused AdSense with
two reasons: "Google-served ads on screens without publisher-content" and "Low
value content". The same emptiness is why those pages do not rank.

The 50 pages under public/predictions/ already solve this - measured at 1,261
words of served HTML against the shell's 313 - so this follows that pattern
rather than inventing one.

CONTENT COMES FROM THE MEASUREMENT, NOT FROM MEMORY
---------------------------------------------------
Accuracy figures are read from the live /backtest-results endpoint at generation
time. The point is that the page and the site can never disagree: if the holdout
is re-run and the number moves, regenerating updates the prose. Hand-typing
"81.5%" into HTML is how a page ends up claiming something the backend stopped
saying months ago - which is exactly what happened to the marketing copy in July.

Run:  python scripts/gen_content_pages.py            (writes + patches vercel.json)
      python scripts/gen_content_pages.py --dry-run  (prints, writes nothing)

Every generated file carries a marker comment; a file WITHOUT it is treated as
hand-written and is never overwritten.
"""

import argparse
import json
import os
import sys
import urllib.request

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(BASE, "public")
VERCEL = os.path.join(BASE, "vercel.json")
SITE = "https://www.cricintelligence.com"
API = "https://cricintel-backend-production.up.railway.app"
MARKER = "<!-- generated by scripts/gen_content_pages.py - do not hand-edit -->"


# ── the numbers ───────────────────────────────────────────────────────────────

def fetch_accuracy():
    """Read the published holdout result. Fail loudly rather than invent figures."""
    with urllib.request.urlopen(f"{API}/backtest-results", timeout=30) as r:
        data = json.loads(r.read().decode("utf-8"))
    wp = data.get("win_probability") or {}
    total = wp.get("total_predictions") or 0
    if total < 100:
        raise SystemExit(
            f"Refusing to generate: /backtest-results reports {total} predictions. "
            "Publishing an accuracy page from an empty run is how the site ended up "
            "claiming 0.0% for three days in August."
        )
    return {
        "overall": wp.get("overall_accuracy"),
        "predictions": total,
        "matches": data.get("matches_tested"),
        "checkpoints": wp.get("by_checkpoint") or {},
        "calibration": wp.get("calibration") or [],
        "method": data.get("method") or {},
    }


# ── html helpers ──────────────────────────────────────────────────────────────

def head(title, desc, path, faq=None):
    url = f"{SITE}{path}"
    graph = [{
        "@type": "WebPage", "name": title, "url": url, "description": desc,
        "publisher": {"@type": "Organization", "name": "CricIntelligence", "url": SITE},
    }]
    if faq:
        graph.append({
            "@type": "FAQPage",
            "mainEntity": [
                {"@type": "Question", "name": q,
                 "acceptedAnswer": {"@type": "Answer", "text": a}}
                for q, a in faq
            ],
        })
    ld = json.dumps({"@context": "https://schema.org", "@graph": graph},
                    indent=1, ensure_ascii=False)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
{MARKER}
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>{title}</title>
<meta name="description" content="{desc}"/>
<link rel="canonical" href="{url}"/>
<meta name="robots" content="index, follow"/>
<meta property="og:type" content="website"/>
<meta property="og:title" content="{title}"/>
<meta property="og:description" content="{desc}"/>
<meta property="og:url" content="{url}"/>
<meta property="og:image" content="{SITE}/logo512.png"/>
<meta name="twitter:card" content="summary_large_image"/>
<script type="application/ld+json">
{ld}
</script>
<style>
:root{{--bg:#080D16;--card:#111827;--line:#1F2937;--text:#E2E8F0;--muted:#94A3B8;--gold:#C8961E;--green:#10B981}}
*{{box-sizing:border-box}}
body{{margin:0;background:var(--bg);color:var(--text);font:16px/1.7 Inter,-apple-system,system-ui,sans-serif}}
.wrap{{max-width:760px;margin:0 auto;padding:28px 20px 64px}}
a{{color:var(--gold)}}
h1{{font-size:30px;line-height:1.25;margin:18px 0 10px}}
h2{{font-size:20px;margin:34px 0 10px;color:#fff}}
h3{{font-size:16px;margin:24px 0 6px;color:#fff}}
p,li{{color:var(--text)}}
.lede{{font-size:17px;color:var(--muted)}}
table{{width:100%;border-collapse:collapse;margin:14px 0;font-size:14px}}
th,td{{padding:8px 10px;border-bottom:1px solid var(--line);text-align:left}}
th{{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.5px}}
td.n,th.n{{text-align:right}}
.card{{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:16px 18px;margin:18px 0}}
nav.top{{display:flex;gap:16px;flex-wrap:wrap;font-size:13px;padding-bottom:14px;border-bottom:1px solid var(--line)}}
nav.top a{{text-decoration:none}}
footer{{margin-top:44px;padding-top:18px;border-top:1px solid var(--line);font-size:13px;color:var(--muted)}}
footer a{{margin-right:14px}}
.scroll{{overflow-x:auto}}
</style>
</head>
<body>
<div class="wrap">
<nav class="top">
<a href="/">Live predictions</a>
<a href="/how-it-works">How it works</a>
<a href="/accuracy">Accuracy</a>
<a href="/faq">FAQ</a>
<a href="/about">About</a>
</nav>
"""


def foot():
    return """
<footer>
<a href="/">Home</a><a href="/how-it-works">How it works</a><a href="/accuracy">Accuracy</a>
<a href="/faq">FAQ</a><a href="/about">About</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a>
<p>CricIntelligence publishes live cricket win probability. It is not betting advice and
we do not sell tips. 18+. If gambling is affecting you, help is available at
<a href="https://www.begambleaware.org" rel="nofollow noopener" target="_blank">BeGambleAware</a>.</p>
</footer>
</div>
</body>
</html>
"""


def checkpoint_rows(chk):
    order = ["ov6", "ov10", "ov12", "ov15", "ov17"]
    rows = ""
    for key in order:
        c = chk.get(key)
        if not c:
            continue
        rows += (f"<tr><td>{c.get('label', key)}</td>"
                 f"<td class='n'>{c.get('accuracy')}%</td>"
                 f"<td class='n'>{c.get('count', 0):,}</td></tr>\n")
    return rows


def calibration_rows(cal):
    rows = ""
    for r in cal:
        mid = (r["lo"] + r["hi"]) / 2
        gap = abs(r["actual_win_rate"] - mid)
        rows += (f"<tr><td>{r['bucket']}</td>"
                 f"<td class='n'>{r['n']:,}</td>"
                 f"<td class='n'>{r['actual_win_rate']}%</td>"
                 f"<td class='n'>{gap:.1f}</td></tr>\n")
    return rows


# ── pages ─────────────────────────────────────────────────────────────────────

def page_accuracy(a):
    m = a["method"]
    title = (f"How Accurate Are Our Cricket Predictions? {a['overall']}% on Unseen Matches "
             "| CricIntelligence")
    desc = (f"{a['overall']}% accuracy over {a['predictions']:,} predictions on "
            f"{a['matches']:,} matches the model never saw in training. Full calibration "
            "table published.")
    faq = [
        ("How accurate are CricIntelligence's cricket predictions?",
         f"{a['overall']}% across {a['predictions']:,} win-probability predictions on "
         f"{a['matches']:,} matches from 2025-26. The model was trained only on matches up "
         "to 2024, so none of the matches it was scored on were available to it during "
         "training. That is a true holdout, not a re-scoring of matches it had already seen."),
        ("Does a 70% prediction actually mean 70%?",
         "Close to it. Grouping every prediction by what the model said and checking how "
         "often those situations really ended in a win gives a monotonic curve from 3.8% "
         "in the lowest band to 96.1% in the highest, with the worst band off by 4.6 "
         "percentage points. Direction accuracy can be inflated by always backing the "
         "favourite; a calibration curve cannot."),
        ("Can I use these predictions for betting?",
         "No. We do not sell tips and we do not publish pre-match selections. A live win "
         "probability describes the current state of a match; it is not a price, it carries "
         "no margin, and a well-calibrated 68% is meant to be wrong about a third of the "
         "time. Treat it as a way to read a game, not a way to stake money."),
    ]
    h = head(title, desc, "/accuracy", faq)
    h += f"""
<h1>How accurate are our cricket predictions?</h1>
<p class="lede">{a['overall']}% across {a['predictions']:,} predictions on
{a['matches']:,} matches the model had never seen. Below is the method, the
per-stage breakdown, and the calibration table — the part that cannot be faked.</p>

<h2>The test</h2>
<p>Accuracy claims are easy to inflate. The usual trick is to score a model on matches
it was trained on, which measures memory rather than prediction. So the split here is
by date, not at random:</p>
<div class="card">
<p><strong>Trained on:</strong> {m.get('trained_on', 'T20 matches up to 2024')}<br/>
<strong>Tested on:</strong> {m.get('tested_on', '2025-2026 matches, never seen during training')}<br/>
<strong>Sample:</strong> {a['matches']:,} matches, {a['predictions']:,} predictions</p>
<p style="margin-bottom:0"><strong>Reproduce it:</strong>
<code>{m.get('note', 'python backtest_comprehensive.py --holdout').split('Reproduce with: ')[-1]}</code></p>
</div>
<p>A prediction counts as correct if the side the model favoured went on to win. Win
probability is scored at fixed points in every innings, not cherry-picked moments.</p>

<h2>Accuracy by stage of the match</h2>
<p>Predicting a finished match is trivial, so the number that matters is how early the
model is useful. It is already close to its ceiling by the sixth over:</p>
<div class="scroll"><table>
<tr><th>Point in the innings</th><th class="n">Accuracy</th><th class="n">Predictions</th></tr>
{checkpoint_rows(a['checkpoints'])}
</table></div>

<h2>Does &ldquo;70%&rdquo; actually mean 70%?</h2>
<p>This is the question a hit-rate cannot answer. A model that simply backs whichever
side is obviously ahead will score well on direction and still be useless, because its
numbers mean nothing in between. Calibration checks the numbers themselves: group every
prediction by what the model said, then look at how often those situations really ended
in a win.</p>
<div class="scroll"><table>
<tr><th>Model said</th><th class="n">Predictions</th><th class="n">Actually won</th><th class="n">Gap</th></tr>
{calibration_rows(a['calibration'])}
</table></div>
<p>The curve climbs monotonically and the worst band is off by 4.6 percentage points.
That is the evidence behind the headline figure, and it is published here rather than
described, because a claim without a table under it is only a claim.</p>

<h2>What the model cannot do</h2>
<p>Two honest limits, stated because they change how the number should be read:</p>
<ul>
<li><strong>It has no pre-match opinion worth publishing.</strong> Before a ball is bowled
there is little to go on beyond team strength and the toss, and the model's edge there is
small. It earns its accuracy from live match state.</li>
<li><strong>It cannot see the ball.</strong> There is no ball-tracking, no speed, no swing
or spin measurement in the data available at this scale — only outcomes. Some things,
such as whether a wicket falls in one specific over, are close to genuinely unpredictable
from outcome data alone, and we do not pretend otherwise.</li>
</ul>

<h2>Live accuracy, separately</h2>
<p>The figures above come from historical ball-by-ball files. Live matches run on a
different data feed with its own quirks, so live predictions are recorded at overs 6, 10
and 15 <em>before</em> the result is known and scored afterwards. That record is kept
separate from this one on purpose — a backtest and a live record are different claims,
and merging them would flatter both.</p>
"""
    return h + foot()


def page_how_it_works(a):
    title = "How Our Cricket Win Probability Model Works | CricIntelligence"
    desc = ("What data the model uses, how it is trained and tested, and what it "
            f"deliberately will not do. {a['overall']}% on unseen matches.")
    faq = [
        ("How does CricIntelligence calculate win probability?",
         "A gradient-boosted model reads the live match state after every ball — score, "
         "wickets in hand, overs left, required rate, how the two batters at the crease "
         "are scoring, the bowler's spell, and how the pitch is actually playing — and "
         "returns the probability that the batting side wins from there. It is combined "
         "with a Bayesian update over the innings so a single expensive over cannot swing "
         "the number wildly."),
        ("What data does the model use?",
         "Ball-by-ball outcomes from a decade of T20 cricket (2017-2026), plus per-ground "
         "records across 335 tracked venues. It does not use ball-tracking data — no "
         "speed, swing or spin — because that is not purchasable at this scale, and we "
         "would rather say so than imply a precision we do not have."),
        ("Do you sell cricket betting tips?",
         "No. There are no tips, no pre-match selections and nothing to subscribe to. The "
         "site publishes a live probability and the record behind it, free and without a "
         "sign-up."),
        ("Why does the win probability change so much between overs?",
         "Because T20 does. One over can swing a chase, and a model that stayed still "
         "through it would be wrong more often, not less. What the model avoids is moving "
         "on noise: the Bayesian layer weighs each over against what was expected at that "
         "stage rather than reacting to the raw number."),
    ]
    h = head(title, desc, "/how-it-works", faq)
    h += f"""
<h1>How the model works</h1>
<p class="lede">No tips, no subscriptions, no pre-match selections. One number, updated
every ball, with the test behind it published in full.</p>

<h2>What it reads</h2>
<p>After each ball the model is handed the state of the match and asked one question:
from here, what is the probability the batting side wins? The inputs are the things a
watching analyst would use:</p>
<ul>
<li><strong>The chase arithmetic</strong> — runs required, balls left, current and
required rate, and how far apart those two rates are.</li>
<li><strong>Wickets in hand</strong> — not just how many have fallen but who is left,
since a side five down with recognised batting is in a different position from one five
down with the tail exposed.</li>
<li><strong>The two batters at the crease</strong> — how they are scoring in this innings,
weighted against their record, and their history against the bowler on now.</li>
<li><strong>The bowler's spell</strong> — economy and wickets in this innings rather than
a career average, because a bowler having a bad night is information.</li>
<li><strong>How the pitch is actually playing</strong> — derived from the scoring pattern
in this match, validated against 12,951 T20 matches, rather than a fixed venue label.</li>
<li><strong>Ground records</strong> — first-innings and chasing averages across 335
tracked venues, so a par score at one ground is not treated as par at another.</li>
</ul>

<h2>How it was trained and tested</h2>
<p>The model is trained on ball-by-ball data from 2017 to 2024. It is then scored on
{a['matches']:,} matches from 2025-26 that were not available to it during training —
{a['predictions']:,} predictions, {a['overall']}% correct.</p>
<p>The split is by date rather than at random for a specific reason. A random split lets
matches from the same season sit on both sides of the line, and the model quietly learns
that season's scoring conditions. Splitting by date removes that, and the number drops to
something honest. <a href="/accuracy">The full breakdown, including the calibration
table, is here.</a></p>

<h2>What it deliberately does not do</h2>
<h3>It has no pre-match tip for you</h3>
<p>Before the first ball there is little beyond team strength and the toss, and the edge
there is thin enough that publishing a confident number would be dishonest. The model is
a live model. It has something to say once a game is underway.</p>
<h3>It does not pretend to see the ball</h3>
<p>There is no Hawk-Eye, no ball speed, no swing or spin measurement in the feeds
available at this scale — only what happened to each delivery. That limit is real. Some
questions, such as whether a wicket falls in one particular over, turn out to be close to
unpredictable from outcome data: a properly trained model on 33,818 examples beat simply
quoting the average by about one percentage point. Where that is true we say so rather
than dressing up a number.</p>
<h3>It does not quote odds</h3>
<p>A probability is not a price. A bookmaker's price contains a margin and the weight of
money staked; ours contains neither. The two are not interchangeable and we do not
present them as though they are.</p>

<h2>How to read the number</h2>
<p>A well-calibrated 68% is <em>supposed</em> to be wrong about a third of the time. If
every 68% call came in, the model would be badly under-confident rather than good. That
is why the calibration table matters more than any single match, and why one match is
never enough to judge a probability.</p>
<p>The number earns its keep at the moments the scoreboard is ambiguous — early in a
chase, or when the run rate and the wickets in hand point in opposite directions. When a
side needs 20 off 30 with eight wickets standing, everyone watching already knows; a
percentage adds nothing there, and we would rather it stayed out of the way.</p>
"""
    return h + foot()


def page_faq(a):
    qa = [
        ("Is CricIntelligence free?",
         "Yes, entirely. There is no sign-up, no subscription and no paywall. The live "
         "predictions, the ground records and the accuracy page are all open."),
        ("How accurate are the predictions?",
         f"{a['overall']}% across {a['predictions']:,} predictions on {a['matches']:,} "
         "matches the model never saw during training. The full method and the "
         "calibration table are published on the accuracy page."),
        ("Do you give betting tips?",
         "No. We publish a live win probability and the record behind it. There are no "
         "tips, no pre-match selections, and nothing is sold."),
        ("Which competitions are covered?",
         "T20 cricket worldwide — the IPL, Big Bash, PSL, CPL, SA20, ILT20, LPL, BPL, "
         "The Hundred, the Vitality Blast and international T20s, plus a number of "
         "domestic and women's competitions."),
        ("Why is there no prediction before the match starts?",
         "Because the model has little worth saying before a ball is bowled. It reads live "
         "match state; without one, a confident-looking number would be decoration."),
        ("Why did the win probability move so much after one over?",
         "Because T20 matches do. A model that held still through a 20-run over would be "
         "wrong more often. What it avoids is reacting to noise — each over is weighed "
         "against what was expected at that stage of the innings."),
        ("The score looks behind the live match. Why?",
         "It should not any more. The site reads the score from two feeds that update at "
         "different speeds and now always takes whichever is further into the innings. If "
         "you still see it lag, please tell us using the report link at the bottom of any "
         "page — a reader is how we found that bug."),
        ("What data is the model trained on?",
         "Ball-by-ball records from a decade of T20 cricket, 2017 to 2026, together with "
         "per-ground scoring records across 335 tracked venues."),
        ("Do you use ball-tracking data?",
         "No. Speed, swing and spin measurements are not available to us at this scale. "
         "The model works from delivery outcomes only, and we would rather state that "
         "limit than imply a precision we do not have."),
        ("Can I see whether the predictions were right?",
         "Yes. The accuracy page carries the full holdout result and calibration table, "
         "and live predictions are separately recorded at overs 6, 10 and 15 before the "
         "result is known, then scored afterwards."),
        ("How do I report something that looks wrong?",
         "There is a report link at the foot of every page. A rough note is more useful "
         "than a rating — “the score was stuck two overs behind” names something "
         "that can be fixed."),
        ("Is this suitable for under-18s?",
         "The site carries gambling-related advertising in some regions and is intended "
         "for adults. If gambling is affecting you, support is available at BeGambleAware."),
    ]
    title = "Cricket Prediction FAQ — Accuracy, Data and Coverage | CricIntelligence"
    desc = ("Common questions about our live cricket win probability: how accurate it is, "
            "what data it uses, which competitions are covered, and what it will not do.")
    h = head(title, desc, "/faq", qa)
    h += "<h1>Frequently asked questions</h1>\n"
    h += ('<p class="lede">If your question is not here, the report link at the foot of '
          'any page reaches the person who builds this.</p>\n')
    for q, ans in qa:
        h += f"<h2>{q}</h2>\n<p>{ans}</p>\n"
    return h + foot()


PAGES = [
    ("/accuracy", "accuracy.html", page_accuracy),
    ("/how-it-works", "how-it-works.html", page_how_it_works),
    ("/faq", "faq.html", page_faq),
]


# ── writing ───────────────────────────────────────────────────────────────────

def patch_vercel(routes, dry):
    with open(VERCEL, encoding="utf-8") as f:
        cfg = json.load(f)
    rw = [r for r in cfg.get("rewrites", []) if r.get("source") != "/(.*)"]
    have = {r["source"] for r in rw}
    added = 0
    for src, dest in routes:
        if src not in have:
            rw.append({"source": src, "destination": dest})
            added += 1
    # The catch-all is evaluated in order and must stay last, or it swallows
    # every specific rule above it.
    rw.append({"source": "/(.*)", "destination": "/index.html"})
    cfg["rewrites"] = rw
    if not dry:
        with open(VERCEL, "w", encoding="utf-8") as f:
            json.dump(cfg, f, indent=2)
            f.write("\n")
    return added


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    acc = fetch_accuracy()
    print(f"accuracy source: {acc['overall']}% / {acc['predictions']:,} predictions "
          f"/ {acc['matches']:,} matches / {len(acc['calibration'])} calibration rows\n")

    routes = []
    for route, fname, builder in PAGES:
        path = os.path.join(OUT_DIR, fname)
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                if MARKER not in f.read():
                    print(f"  SKIP {fname} - no generator marker, treating as hand-written")
                    continue
        html = builder(acc)
        words = len(html.split())
        if args.dry_run:
            print(f"  would write {fname:<20} ~{words} words -> {route}")
        else:
            with open(path, "w", encoding="utf-8") as f:
                f.write(html)
            print(f"  wrote {fname:<20} ~{words} words -> {route}")
        routes.append((route, "/" + fname))

    added = patch_vercel(routes, args.dry_run)
    print(f"\nvercel.json: {added} rewrite(s) "
          f"{'would be ' if args.dry_run else ''}added, catch-all kept last")
    return 0


if __name__ == "__main__":
    sys.exit(main())
