#!/usr/bin/env python3
"""
A prerendered page per cricket ground, built from our own scoring records.

WHY THIS AND NOT MORE MODEL WORK
--------------------------------
Of 84 logged backend sessions, 56% were model or accuracy work and 1% was about
getting anyone to use the site. The model is not the problem - it scores 81.5%
on a true holdout with a published calibration table, which is more than CricViz
publishes for WinViz. The problem is that nobody searches for "win probability".

People do search for a ground by name before a match: what it scores, whether
chasing works there, whether it has changed. We hold that data for 335 venues
and have never published a word of it. It is the one asset on this site that no
competitor has - CricTracker and the rest write a pitch report from opinion.

WHAT MAKES A PAGE WORTH PUBLISHING
----------------------------------
Not a template with a name swapped in - that is a doorway page and Google is
right to ignore it. Every number here is specific to the ground and computed,
never written: phase-by-phase run rates and wickets for BOTH innings, the
batting-first advantage, and a recent-versus-all-time comparison that says
whether the surface has drifted. Two grounds produce genuinely different prose
because the arithmetic differs.

MIN_MATCHES is 20 on purpose. Below that the phase splits are noise dressed as
insight, which is the exact mistake this codebase has made before with
small-sample calibration. 121 of 335 venues clear it.

PURELY ADDITIVE. No React component changes, no existing file rewritten. New
HTML under public/venues/, new rewrites appended before the catch-all, new
sitemap entries.

Run:  python scripts/gen_venue_pages.py              (writes + patches)
      python scripts/gen_venue_pages.py --dry-run
      python scripts/gen_venue_pages.py --min 30     (fewer, richer pages)
"""

import argparse
import json
import os
import re
import sys
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import league_data  # curated, de-duplicated ground tables per league

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(BASE, "public", "venues")
VERCEL = os.path.join(BASE, "vercel.json")
SITEMAP = os.path.join(BASE, "public", "sitemap.xml")
SITE = "https://www.cricintelligence.com"
API = "https://cricintel-backend-production.up.railway.app"
MARKER = "<!-- generated by scripts/gen_venue_pages.py - do not hand-edit -->"

# The backend repo sits beside this one. venue_stats.json is the single source
# of truth for every ground figure on the site - the same file that settled the
# "877 venues" claim as false (it holds 335).
VENUE_JSON = os.path.join(
    os.path.dirname(BASE), "cricintel-backend", "venue_stats.json")

MIN_MATCHES = 20
PHASES = [("1-4", "Powerplay"), ("5-8", "Early middle"), ("9-12", "Middle"),
          ("13-16", "Late middle"), ("17-20", "Death")]


# ── inputs ────────────────────────────────────────────────────────────────────

def fetch_accuracy():
    """The published holdout figure. Never typed into a page by hand."""
    with urllib.request.urlopen(API + "/backtest-results", timeout=30) as r:
        d = json.loads(r.read().decode("utf-8"))
    wp = d.get("win_probability") or {}
    n = wp.get("total_predictions") or 0
    if n < 100:
        raise SystemExit(
            "Refusing to generate: /backtest-results reports %d predictions. "
            "That is the state that put 0.0%% on the public accuracy page in "
            "August 2026." % n)
    return {"overall": wp.get("overall_accuracy"), "preds": n,
            "matches": d.get("matches_tested")}


def load_venues(min_matches):
    """Only grounds a person would actually search for, merged across duplicate keys.

    A first pass selected purely on match count and it was wrong twice over:

      * Match count does not track searchability. Terdthai Cricket Ground in
        Bangkok has 96 recorded matches and nobody has ever looked it up;
        Edgbaston has 22 and everybody has. Publishing 120 pages selected that
        way produced entries for a German club ground - the exact doorway-page
        pattern Google is right to ignore, and the last thing a site already
        refused by AdSense for "low value content" should ship.
      * The same ground appears under several keys. "Wankhede Stadium" (80
        matches) and "Wankhede Stadium, Mumbai" (64) are one ground; so are the
        two spellings of Gahanga. That would have published two pages for one
        venue with different numbers on each.

    league_data.GROUNDS already solves both - it is hand-curated per league and
    groups every alias of a ground under one display name, which is why it exists
    (see the frontend CLAUDE.md note about "oval" matching Botswana). 56 grounds,
    every one a real venue in a competition this site covers.
    """
    if not os.path.exists(VENUE_JSON):
        raise SystemExit("venue_stats.json not found at %s - this generator "
                         "reads the backend repo beside this one." % VENUE_JSON)
    raw = json.load(open(VENUE_JSON, encoding="utf-8"))

    leagues = {}
    for lg, rows in league_data.GROUNDS.items():
        for display, keys in rows:
            leagues.setdefault(display, {"keys": set(), "leagues": set()})
            leagues[display]["keys"].update(keys)
            leagues[display]["leagues"].add(lg)

    out = []
    for display, meta in leagues.items():
        present = [k for k in meta["keys"] if k in raw]
        if not present:
            continue
        merged = league_data._merge(raw, present)
        if not merged or (merged.get("n") or 0) < min_matches:
            continue
        # _merge returns aggregates only; segments come from the richest key so
        # the phase splits are never averaged across differently-shaped samples.
        best = max(present, key=lambda k: raw[k].get("match_count", 0))
        src = raw[best]
        if not (src.get("segments") or {}).get("inn1"):
            continue
        out.append({
            "key": best,
            "name": display,
            "slug": slugify(display),
            "match_count": merged["n"],
            "avg_first_innings": merged["first"],
            "avg_second_innings": merged["second"],
            "overall_avg_rpo": merged.get("rpo"),
            "segments": src.get("segments"),
            "recent_segments": src.get("recent_segments"),
            "recent_match_count": src.get("recent_match_count"),
            "leagues": sorted(meta["leagues"]),
        })
    out.sort(key=lambda x: -x["match_count"])
    return out


def slugify(name):
    s = re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")
    return re.sub(r"-+", "-", s)


# ── reading the numbers ───────────────────────────────────────────────────────

def seg(v, inn, label, key="avg_rpo", recent=False):
    src = (v.get("recent_segments") if recent else v.get("segments")) or {}
    for s in src.get(inn, []):
        if s.get("label") == label:
            return s.get(key)
    return None


def describe(v):
    """Turn one ground's numbers into the sentences that make it its own page."""
    first = v.get("avg_first_innings") or 0
    second = v.get("avg_second_innings") or 0
    gap = round(first - second, 1)

    d1 = seg(v, "inn1", "17-20") or 0
    d2 = seg(v, "inn2", "17-20") or 0
    pp1 = seg(v, "inn1", "1-4") or 0

    # Has the surface drifted? Compare recent death overs with all-time.
    rd1 = seg(v, "inn1", "17-20", recent=True)
    drift = round(rd1 - d1, 2) if rd1 is not None and d1 else None

    if gap >= 15:
        toss = ("a real batting-first advantage - sides batting second average "
                "%.1f runs fewer" % gap)
    elif gap >= 6:
        toss = "a modest edge to batting first, worth about %.0f runs" % gap
    elif gap <= -6:
        toss = ("an edge to CHASING - sides batting second average %.1f runs "
                "more" % abs(gap))
    else:
        toss = ("almost no toss advantage either way - %.1f runs separates the "
                "two innings" % abs(gap))

    if d1 and d2:
        dd = round(d1 - d2, 2)
        if dd >= 1.5:
            death = ("Chases stall here. The last four overs go at %.2f an over "
                     "batting first and only %.2f batting second - a %.2f-run "
                     "collapse in the phase that usually decides a T20."
                     % (d1, d2, dd))
        elif dd <= -1.0:
            death = ("Chases finish strongly here. The last four overs go at "
                     "%.2f an over batting second against %.2f batting first, "
                     "so a target that looks safe often is not." % (d2, d1))
        else:
            death = ("The death overs behave much the same in both innings - "
                     "%.2f an over batting first, %.2f chasing." % (d1, d2))
    else:
        death = ""

    if drift is not None and abs(drift) >= 0.6:
        way = "higher" if drift > 0 else "lower"
        move = ("Recent matches are scoring %s than the all-time record: %.2f "
                "an over at the death against %.2f across the full sample, so "
                "the older figures understate%s what happens now."
                % (way, rd1, d1, "" if drift > 0 else " the difficulty of"))
    elif drift is not None:
        move = ("Recent matches track the long-run record closely, so the "
                "figures below are not being dragged by an old era.")
    else:
        move = ""

    return {"gap": gap, "toss": toss, "death": death, "move": move,
            "first": first, "second": second, "pp1": pp1}


def phase_table(v):
    rows = ""
    for label, name in PHASES:
        r1, w1 = seg(v, "inn1", label), seg(v, "inn1", label, "avg_wickets")
        r2, w2 = seg(v, "inn2", label), seg(v, "inn2", label, "avg_wickets")
        if r1 is None and r2 is None:
            continue
        fmt = lambda x, n=2: "-" if x is None else ("%.*f" % (n, x))
        rows += ('<tr><td>%s <span class="mut">(ov %s)</span></td>'
                 '<td class="n">%s</td><td class="n">%s</td>'
                 '<td class="n">%s</td><td class="n">%s</td></tr>'
                 % (name, label, fmt(r1), fmt(w1, 1), fmt(r2), fmt(w2, 1)))
    return ('<div class="scroll"><table>'
            '<tr><th rowspan="2">Phase</th><th colspan="2" class="n">Batting first</th>'
            '<th colspan="2" class="n">Chasing</th></tr>'
            '<tr><th class="n">Runs/over</th><th class="n">Wickets</th>'
            '<th class="n">Runs/over</th><th class="n">Wickets</th></tr>'
            + rows + "</table></div>")



def par_table(v):
    """A running par score - what the total reads at the end of each phase.

    This is the number a viewer actually wants and no competitor publishes it:
    "is 60 for 2 after 8 overs good HERE". Built by accumulating the measured
    phase run rates rather than dividing a final average into equal chunks,
    which would erase the whole point.
    """
    rows = ""
    for inn, label in (("inn1", "Batting first"), ("inn2", "Chasing")):
        runs = wkts = 0.0
        cells = ""
        ok = False
        for lab, _ in PHASES:
            r = seg(v, inn, lab)
            w = seg(v, inn, lab, "avg_wickets")
            if r is None:
                cells += '<td class="n">-</td>'
                continue
            ok = True
            overs = 4 if lab != "17-20" else 4
            runs += r * overs
            wkts += (w or 0)
            cells += '<td class="n">%d-%d</td>' % (round(runs), round(wkts))
        if ok:
            rows += "<tr><td>%s</td>%s</tr>" % (label, cells)
    if not rows:
        return ""
    heads = "".join('<th class="n">%s ov</th>' % lab.split("-")[1]
                    for lab, _ in PHASES)
    return ('<div class="scroll"><table><tr><th>Par score after</th>%s</tr>%s'
            "</table></div>" % (heads, rows))


def recent_table(v):
    """Recent form against the long-run record, phase by phase."""
    if not (v.get("recent_segments") or {}).get("inn1"):
        return ""
    rows = ""
    for lab, name in PHASES:
        a_ = seg(v, "inn1", lab)
        r_ = seg(v, "inn1", lab, recent=True)
        if a_ is None or r_ is None:
            continue
        d = r_ - a_
        arrow = "&#9650;" if d > 0.25 else ("&#9660;" if d < -0.25 else "&ndash;")
        rows += ('<tr><td>%s <span class="mut">(ov %s)</span></td>'
                 '<td class="n">%.2f</td><td class="n">%.2f</td>'
                 '<td class="n">%s %+.2f</td></tr>'
                 % (name, lab, a_, r_, arrow, d))
    if not rows:
        return ""
    n = v.get("recent_match_count") or 0
    return ('<div class="scroll"><table>'
            '<tr><th>Phase</th><th class="n">All-time</th>'
            '<th class="n">Last %d</th><th class="n">Change</th></tr>%s'
            "</table></div>" % (n, rows))


def volatility(v):
    """How predictable this ground is - the part a probability model cares about."""
    stds = [seg(v, "inn1", lab, "std_rpo") for lab, _ in PHASES]
    stds = [x for x in stds if x]
    if not stds:
        return ""
    avg = sum(stds) / len(stds)
    death = seg(v, "inn1", "17-20", "std_rpo")
    if avg >= 2.9:
        verdict = ("a volatile ground - over-to-over scoring swings widely, so a "
                   "required rate here is less reliable than the same rate elsewhere")
    elif avg <= 2.2:
        verdict = ("a predictable ground - scoring holds close to its average from "
                   "over to over, so a required rate here means what it says")
    else:
        verdict = "about as predictable as a typical T20 ground"
    d = (" The death overs are the loosest part at %.2f." % death) if death else ""
    return ("<p>Measured over-to-over variation averages %.2f runs, which makes this "
            "%s.%s</p>" % (avg, verdict, d))


# ── html ──────────────────────────────────────────────────────────────────────

def page(v, a, total):
    name = v.get("name") or v["key"].title()
    n = v["match_count"]
    d = describe(v)
    url = "%s/venues/%s" % (SITE, v["slug"])
    title = "%s — T20 Pitch Report and Scoring Record" % name
    desc = ("%s T20 scoring record over %d matches: %.0f average first innings, "
            "%.0f chasing, phase-by-phase run rates and what it means for a "
            "chase." % (name, n, d["first"], d["second"]))

    faq = [
        ("What is the average first-innings score at %s?" % name,
         "%.0f across %d recorded T20 matches, against %.0f batting second."
         % (d["first"], n, d["second"])),
        ("Is it better to bat or chase at %s?" % name,
         "The record shows %s." % d["toss"]),
        ("How many matches is this based on?",
         "%d T20 matches at this ground, from ball-by-ball records." % n),
    ]
    ld = json.dumps({"@context": "https://schema.org", "@graph": [
        {"@type": "WebPage", "name": title, "url": url, "description": desc,
         "publisher": {"@type": "Organization", "name": "CricIntelligence",
                       "url": SITE}},
        {"@type": "FAQPage", "mainEntity": [
            {"@type": "Question", "name": q,
             "acceptedAnswer": {"@type": "Answer", "text": ans}}
            for q, ans in faq]},
    ]}, indent=1, ensure_ascii=False)

    return """<!DOCTYPE html>
<html lang="en">
<head>
%s
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>%s</title>
<meta name="description" content="%s"/>
<link rel="canonical" href="%s"/>
<meta name="robots" content="index, follow"/>
<meta property="og:type" content="website"/>
<meta property="og:title" content="%s"/>
<meta property="og:description" content="%s"/>
<meta property="og:url" content="%s"/>
<script type="application/ld+json">
%s
</script>
<style>
:root{--bg:#080D16;--card:#111827;--line:#1F2937;--text:#E2E8F0;--muted:#94A3B8;--gold:#C8961E;--green:#10B981}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--text);font:16px/1.7 Inter,-apple-system,system-ui,sans-serif}
.wrap{max-width:760px;margin:0 auto;padding:28px 20px 64px}
a{color:var(--gold)}
h1{font-size:28px;line-height:1.25;margin:18px 0 10px}
h2{font-size:20px;margin:32px 0 10px;color:#fff}
.lede{font-size:17px;color:var(--muted)}
.mut{color:var(--muted);font-size:12px}
table{width:100%%;border-collapse:collapse;margin:14px 0;font-size:14px}
th,td{padding:8px 10px;border-bottom:1px solid var(--line);text-align:left}
th{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.5px}
td.n,th.n{text-align:right}
.stats{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}
.stat{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:12px 16px;flex:1;min-width:130px}
.stat b{display:block;font-size:26px;color:#fff;line-height:1.2}
.stat span{font-size:12px;color:var(--muted);text-transform:uppercase;letter-spacing:.5px}
nav.top{display:flex;gap:16px;flex-wrap:wrap;font-size:13px;padding-bottom:14px;border-bottom:1px solid var(--line)}
nav.top a{text-decoration:none}
footer{margin-top:44px;padding-top:18px;border-top:1px solid var(--line);font-size:13px;color:var(--muted)}
footer a{margin-right:14px}
.scroll{overflow-x:auto}
</style>
</head>
<body>
<div class="wrap">
<nav class="top">
<a href="/">Live predictions</a><a href="/venues">All grounds</a>
<a href="/accuracy">Accuracy</a><a href="/how-it-works">How it works</a><a href="/faq">FAQ</a>
</nav>

<h1>%s — T20 pitch report and scoring record</h1>
<p class="lede">What this ground actually produces, measured across %d T20 matches of
ball-by-ball records rather than described from memory.</p>

<div class="stats">
<div class="stat"><b>%.0f</b><span>Avg 1st innings</span></div>
<div class="stat"><b>%.0f</b><span>Avg chasing</span></div>
<div class="stat"><b>%.2f</b><span>Runs per over</span></div>
<div class="stat"><b>%d</b><span>Matches</span></div>
</div>

<h2>Bat or chase?</h2>
<p>The record shows %s.</p>
<p>%s</p>

<h2>Phase by phase</h2>
<p>Average runs and wickets per phase, split by innings. This is where a ground gives
itself away: a par score is not one number, it is a shape.</p>
%s
<p>%s</p>

<h2>Par score, phase by phase</h2>
<p>What the total actually reads at the end of each phase &mdash; built from this
ground's own measured run rates, not by dividing a final average into equal pieces.
This is what "is 60 for 2 after 8 a good position" means here.</p>
%s

<h2>Has it changed lately?</h2>
%s

<h2>How predictable is it?</h2>
%s

<h2>Reading a chase here</h2>
<p>A required rate means different things at different grounds. At %s the powerplay
goes at %.2f an over batting first, so a chase that is level with the rate after four
overs is genuinely level &mdash; not ahead, and not behind. The phase table above is
what the model uses to judge that, rather than a single national average.</p>

<h2>Where these numbers come from</h2>
<p>Ball-by-ball records for every T20 played at this ground in the dataset, aggregated
per phase and per innings. The same records feed the live win probability on this site,
which scores <strong>%s%%</strong> across %s predictions on %s matches it had never
seen during training &mdash; the method and calibration table are on the
<a href="/accuracy">accuracy page</a>.</p>
<p>No ball-tracking is used: speed, swing and spin measurements are not available at
this scale, and these figures are delivery outcomes only.</p>

<p><a href="/">See live predictions</a> &middot;
<a href="/venues">All %d grounds</a> &middot;
<a href="/predictions/cricket-win-probability">How win probability works</a></p>

<footer>
<a href="/">Home</a><a href="/venues">Grounds</a><a href="/accuracy">Accuracy</a>
<a href="/faq">FAQ</a><a href="/about">About</a><a href="/privacy">Privacy</a>
<p>CricIntelligence publishes live cricket win probability. It is not betting advice and
we do not sell tips. 18+.</p>
</footer>
</div>
</body>
</html>
""" % (MARKER, title, desc, url, title, desc, url, ld,
       name, n, d["first"], d["second"], v.get("overall_avg_rpo") or 0, n,
       d["toss"], d["move"] or "", phase_table(v), d["death"] or "",
       par_table(v), recent_table(v) or "<p>Not enough recent matches to compare.</p>",
       volatility(v) or "",
       name, d["pp1"] or 0,
       a["overall"], "{:,}".format(a["preds"]), "{:,}".format(a["matches"]),
       total)


HTML = """<!DOCTYPE html>
<html lang="en">
<head>
%s
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>%s</title>
<meta name="description" content="%s"/>
<link rel="canonical" href="%s/venues"/>
<meta name="robots" content="index, follow"/>
<meta property="og:title" content="%s"/>
<meta property="og:description" content="%s"/>
<meta property="og:url" content="%s/venues"/>
<style>
:root{background:#080D16}
body{margin:0;background:#080D16;color:#E2E8F0;font:16px/1.7 Inter,-apple-system,system-ui,sans-serif}
.wrap{max-width:880px;margin:0 auto;padding:28px 20px 64px}
a{color:#C8961E}h1{font-size:30px;line-height:1.25;margin:18px 0 10px}
h2{font-size:20px;margin:34px 0 10px;color:#fff}
.lede{color:#94A3B8;font-size:17px}
.mut{color:#94A3B8}
table{width:100%%;border-collapse:collapse;margin:16px 0;font-size:14px}
th,td{padding:8px 10px;border-bottom:1px solid #1F2937;text-align:left}
th{color:#94A3B8;font-size:12px;text-transform:uppercase;letter-spacing:.5px}
td.n,th.n{text-align:right}
.stats{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}
.stat{background:#111827;border:1px solid #1F2937;border-radius:12px;padding:12px 16px;flex:1;min-width:150px}
.stat b{display:block;font-size:24px;color:#fff;line-height:1.2}
.stat span{font-size:12px;color:#94A3B8;text-transform:uppercase}
nav.top{display:flex;gap:16px;font-size:13px;padding-bottom:14px;border-bottom:1px solid #1F2937}
nav.top a{text-decoration:none}
footer{margin-top:44px;padding-top:18px;border-top:1px solid #1F2937;font-size:13px;color:#94A3B8}
footer a{margin-right:14px}
.scroll{overflow-x:auto}
</style>
</head>
<body>
<div class="wrap">
<nav class="top"><a href="/">Live predictions</a><a href="/accuracy">Accuracy</a>
<a href="/how-it-works">How it works</a><a href="/faq">FAQ</a></nav>

<h1>Highest and lowest scoring T20 grounds</h1>
<p class="lede">%d grounds ranked by what a first innings actually averages there,
measured from ball-by-ball records rather than described from memory.</p>

<div class="stats">
<div class="stat"><b>%.0f</b><span>%s</span></div>
<div class="stat"><b>%.0f</b><span>%s</span></div>
<div class="stat"><b>%.0f runs</b><span>Spread between them</span></div>
</div>

<p>That is a <strong>%.0f-run gap</strong> between the highest and lowest scoring
grounds in this set &mdash; more than a whole powerplay. It is why &ldquo;a good
total&rdquo; is a question with no general answer, and why reading a chase against a
single national par score gets it wrong at both ends.</p>

<h2>Why first innings, and not a chase-success ranking</h2>
<p>The obvious ranking to publish would be &ldquo;hardest grounds to chase at&rdquo;. We
computed it and threw it away. Every ground in the set appears to punish chasing, which
is not a fact about pitches: <strong>a successful chase stops the moment the target is
passed</strong>, so the only chases that reach the death overs are the ones already
going badly. Any ranking built on that measures the format, not the ground.</p>
<p>A first innings plays its full twenty overs. Its average is clean, comparable across
grounds, and is the number actually worth knowing before a match.</p>

<h2>All %d grounds</h2>
<div class="scroll"><table>
<tr><th class="n">#</th><th>Ground</th><th class="n">Matches</th>
<th class="n">1st inns</th><th class="n">2nd inns</th><th class="n">Runs/over</th></tr>
%s
</table></div>

<h2>Which grounds accelerate, and which stay flat</h2>
<p>A ground&rsquo;s average hides its shape. Some climb steeply from the powerplay to
the death; others score at nearly the same rate throughout, which changes what a
required rate means at every stage. Top five and bottom five, first innings:</p>
<div class="scroll"><table>
<tr><th>Ground</th><th class="n">Powerplay</th><th class="n">Death</th><th class="n">Change</th></tr>
%s
</table></div>

<h2>Where these come from</h2>
<p>Ball-by-ball records for every T20 played at each ground in the dataset. The same
records feed the live win probability on this site, measured at <strong>%s%%</strong>
across %s predictions on %s matches it had never seen during training &mdash; method and
calibration table on the <a href="/accuracy">accuracy page</a>. No ball-tracking is
used; these are delivery outcomes only.</p>

<footer>
<a href="/">Home</a><a href="/accuracy">Accuracy</a><a href="/how-it-works">How it works</a>
<a href="/faq">FAQ</a><a href="/about">About</a>
<p>CricIntelligence publishes live cricket win probability. It is not betting advice and
we do not sell tips. 18+.</p>
</footer>
</div>
</body>
</html>
"""


def index_page(venues, a):
    """A ranking, not a directory.

    WHY FIRST-INNINGS AVERAGE AND NOT "HARDEST TO CHASE"
    ---------------------------------------------------
    A chase-difficulty ranking was computed first and thrown away. Every single
    ground showed batting-first scoring more at the death, which is not a fact
    about pitches - a successful chase STOPS the moment the target is passed, so
    the only chases reaching the death overs are the ones already going badly.
    Both the death-over gap and the raw first-versus-second innings gap are
    contaminated by that, and this repo has already published two claims built on
    numbers nobody checked that hard.

    A first innings plays its full twenty overs. Its average is clean, comparable
    across grounds, and is the number a viewer actually wants before a match.
    """
    vs = sorted(venues, key=lambda v: -(v.get("avg_first_innings") or 0))
    hi, lo = vs[0], vs[-1]
    spread = (hi.get("avg_first_innings") or 0) - (lo.get("avg_first_innings") or 0)

    acc = []
    for v in vs:
        p_, d_ = seg(v, "inn1", "1-4"), seg(v, "inn1", "17-20")
        if p_ and d_:
            acc.append((d_ - p_, v))
    acc.sort(key=lambda x: -x[0])

    rows = "".join(
        '<tr><td class="n mut">%d</td><td><a href="/venues/%s">%s</a></td>'
        '<td class="n">%d</td><td class="n"><b>%.0f</b></td>'
        '<td class="n">%.0f</td><td class="n">%.2f</td></tr>'
        % (i + 1, v["slug"], v.get("name"), v["match_count"],
           v.get("avg_first_innings") or 0, v.get("avg_second_innings") or 0,
           v.get("overall_avg_rpo") or 0)
        for i, v in enumerate(vs))

    acc_rows = "".join(
        '<tr><td>%s</td><td class="n">%.2f</td><td class="n">%.2f</td>'
        '<td class="n">%+.2f</td></tr>'
        % (v.get("name"), seg(v, "inn1", "1-4"), seg(v, "inn1", "17-20"), d)
        for d, v in (acc[:5] + acc[-5:]))

    title = ("Highest and Lowest Scoring T20 Cricket Grounds - %d Venues Ranked"
             % len(vs))
    desc = ("%d T20 grounds ranked by first-innings average, from %s at %.0f down "
            "to %s at %.0f. Measured from ball-by-ball records, not opinion."
            % (len(vs), hi.get("name"), hi.get("avg_first_innings") or 0,
               lo.get("name"), lo.get("avg_first_innings") or 0))

    return HTML % (MARKER, title, desc, SITE, title, desc, SITE,
                   len(vs),
                   hi.get("avg_first_innings") or 0, hi.get("name"),
                   lo.get("avg_first_innings") or 0, lo.get("name"),
                   spread, spread, len(vs), rows, acc_rows,
                   a["overall"], "{:,}".format(a["preds"]),
                   "{:,}".format(a["matches"]))


# ── writing ───────────────────────────────────────────────────────────────────

def patch_vercel(routes, dry):
    cfg = json.load(open(VERCEL, encoding="utf-8"))
    rw = [r for r in cfg.get("rewrites", []) if r.get("source") != "/(.*)"]
    have = {r["source"] for r in rw}
    added = 0
    for src, dest in routes:
        if src not in have:
            rw.append({"source": src, "destination": dest})
            added += 1
    # Evaluated in order - the catch-all must stay last or it swallows every
    # specific rule above it.
    rw.append({"source": "/(.*)", "destination": "/index.html"})
    cfg["rewrites"] = rw
    if not dry:
        with open(VERCEL, "w", encoding="utf-8") as f:
            json.dump(cfg, f, indent=2)
            f.write("\n")
    return added


def patch_sitemap(paths, dry):
    body = open(SITEMAP, encoding="utf-8").read()
    added = 0
    block = ""
    for p in paths:
        if p in body:
            continue
        block += ("  <url><loc>%s%s</loc><changefreq>monthly</changefreq>"
                  "<priority>0.7</priority></url>\n" % (SITE, p))
        added += 1
    if block and not dry:
        body = body.replace("</urlset>", block + "</urlset>")
        open(SITEMAP, "w", encoding="utf-8").write(body)
    return added


def main():
    global MIN_MATCHES
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--min", type=int, default=MIN_MATCHES)
    args = ap.parse_args()
    MIN_MATCHES = args.min

    a = fetch_accuracy()
    print("accuracy source: %s%% / %s predictions / %s matches\n"
          % (a["overall"], "{:,}".format(a["preds"]), "{:,}".format(a["matches"])))

    venues = load_venues(args.min)
    print("venues with >= %d matches: %d\n" % (args.min, len(venues)))
    if not venues:
        raise SystemExit("No venues cleared the threshold - nothing to write.")

    if not args.dry_run:
        os.makedirs(OUT_DIR, exist_ok=True)

    routes, paths = [], []
    for v in venues:
        html = page(v, a, len(venues))
        rel = "venues/%s.html" % v["slug"]
        if not args.dry_run:
            open(os.path.join(BASE, "public", rel), "w", encoding="utf-8").write(html)
        routes.append(("/venues/%s" % v["slug"], "/" + rel))
        paths.append("/venues/%s" % v["slug"])

    idx = index_page(venues, a)
    if not args.dry_run:
        open(os.path.join(BASE, "public", "venues.html"), "w",
             encoding="utf-8").write(idx)
    routes.append(("/venues", "/venues.html"))
    paths.append("/venues")

    print("%s %d ground pages + 1 index" %
          ("would write" if args.dry_run else "wrote", len(venues)))
    n = patch_vercel(routes, args.dry_run)
    m = patch_sitemap(paths, args.dry_run)
    print("vercel.json: %d rewrite(s) %s, catch-all kept last"
          % (n, "would be added" if args.dry_run else "added"))
    print("sitemap.xml: %d url(s) %s"
          % (m, "would be added" if args.dry_run else "added"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
